data:
  raw_path: "data/WA_Fn-UseC_-Telco-Customer-Churn.csv"

model:
  save_path: "models/churn_model.pkl"
  type: "decision_tree"
  params:
    max_depth: 5
    random_state: 42

train:
  test_size: 0.2
  stratify: true
  random_state: 42
